# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `lint_roller` gem.
# Please instead update this file by running `bin/tapioca gem lint_roller`.


# source://lint_roller//lib/lint_roller/context.rb#1
module LintRoller; end

# source://lint_roller//lib/lint_roller/about.rb#2
class LintRoller::About < ::Struct
  # source://lint_roller//lib/lint_roller/about.rb#2
  def description; end

  # source://lint_roller//lib/lint_roller/about.rb#2
  def description=(_); end

  # source://lint_roller//lib/lint_roller/about.rb#2
  def homepage; end

  # source://lint_roller//lib/lint_roller/about.rb#2
  def homepage=(_); end

  # source://lint_roller//lib/lint_roller/about.rb#2
  def name; end

  # source://lint_roller//lib/lint_roller/about.rb#2
  def name=(_); end

  # source://lint_roller//lib/lint_roller/about.rb#2
  def version; end

  # source://lint_roller//lib/lint_roller/about.rb#2
  def version=(_); end

  class << self
    # source://lint_roller//lib/lint_roller/about.rb#2
    def [](*_arg0); end

    # source://lint_roller//lib/lint_roller/about.rb#2
    def inspect; end

    # source://lint_roller//lib/lint_roller/about.rb#2
    def keyword_init?; end

    # source://lint_roller//lib/lint_roller/about.rb#2
    def members; end

    # source://lint_roller//lib/lint_roller/about.rb#2
    def new(*_arg0); end
  end
end

# source://lint_roller//lib/lint_roller/context.rb#2
class LintRoller::Context < ::Struct
  # source://lint_roller//lib/lint_roller/context.rb#2
  def engine; end

  # source://lint_roller//lib/lint_roller/context.rb#2
  def engine=(_); end

  # source://lint_roller//lib/lint_roller/context.rb#2
  def engine_version; end

  # source://lint_roller//lib/lint_roller/context.rb#2
  def engine_version=(_); end

  # source://lint_roller//lib/lint_roller/context.rb#2
  def rule_format; end

  # source://lint_roller//lib/lint_roller/context.rb#2
  def rule_format=(_); end

  # source://lint_roller//lib/lint_roller/context.rb#2
  def runner; end

  # source://lint_roller//lib/lint_roller/context.rb#2
  def runner=(_); end

  # source://lint_roller//lib/lint_roller/context.rb#2
  def runner_version; end

  # source://lint_roller//lib/lint_roller/context.rb#2
  def runner_version=(_); end

  # source://lint_roller//lib/lint_roller/context.rb#2
  def target_ruby_version; end

  # source://lint_roller//lib/lint_roller/context.rb#2
  def target_ruby_version=(_); end

  class << self
    # source://lint_roller//lib/lint_roller/context.rb#2
    def [](*_arg0); end

    # source://lint_roller//lib/lint_roller/context.rb#2
    def inspect; end

    # source://lint_roller//lib/lint_roller/context.rb#2
    def keyword_init?; end

    # source://lint_roller//lib/lint_roller/context.rb#2
    def members; end

    # source://lint_roller//lib/lint_roller/context.rb#2
    def new(*_arg0); end
  end
end

# source://lint_roller//lib/lint_roller/error.rb#2
class LintRoller::Error < ::StandardError; end

# source://lint_roller//lib/lint_roller/plugin.rb#2
class LintRoller::Plugin
  # source://lint_roller//lib/lint_roller/plugin.rb#4
  def initialize(config = T.unsafe(nil)); end

  # source://lint_roller//lib/lint_roller/plugin.rb#8
  def about; end

  # source://lint_roller//lib/lint_roller/plugin.rb#18
  def rules(context); end

  # source://lint_roller//lib/lint_roller/plugin.rb#13
  def supported?(context); end
end

# source://lint_roller//lib/lint_roller/rules.rb#2
class LintRoller::Rules < ::Struct
  # source://lint_roller//lib/lint_roller/rules.rb#2
  def config_format; end

  # source://lint_roller//lib/lint_roller/rules.rb#2
  def config_format=(_); end

  # source://lint_roller//lib/lint_roller/rules.rb#2
  def error; end

  # source://lint_roller//lib/lint_roller/rules.rb#2
  def error=(_); end

  # source://lint_roller//lib/lint_roller/rules.rb#2
  def type; end

  # source://lint_roller//lib/lint_roller/rules.rb#2
  def type=(_); end

  # source://lint_roller//lib/lint_roller/rules.rb#2
  def value; end

  # source://lint_roller//lib/lint_roller/rules.rb#2
  def value=(_); end

  class << self
    # source://lint_roller//lib/lint_roller/rules.rb#2
    def [](*_arg0); end

    # source://lint_roller//lib/lint_roller/rules.rb#2
    def inspect; end

    # source://lint_roller//lib/lint_roller/rules.rb#2
    def keyword_init?; end

    # source://lint_roller//lib/lint_roller/rules.rb#2
    def members; end

    # source://lint_roller//lib/lint_roller/rules.rb#2
    def new(*_arg0); end
  end
end

# source://lint_roller//lib/lint_roller/support/merges_upstream_metadata.rb#2
module LintRoller::Support; end

# source://lint_roller//lib/lint_roller/support/merges_upstream_metadata.rb#3
class LintRoller::Support::MergesUpstreamMetadata
  # source://lint_roller//lib/lint_roller/support/merges_upstream_metadata.rb#4
  def merge(plugin_yaml, upstream_yaml); end
end

# source://lint_roller//lib/lint_roller/version.rb#2
LintRoller::VERSION = T.let(T.unsafe(nil), String)
