# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rspec-sidekiq` gem.
# Please instead update this file by running `bin/tapioca gem rspec-sidekiq`.


# source://rspec-sidekiq//lib/rspec/sidekiq/configuration.rb#6
module RSpec; end

# source://rspec-sidekiq//lib/rspec/sidekiq/configuration.rb#7
module RSpec::Sidekiq
  class << self
    # source://rspec-sidekiq//lib/rspec/sidekiq/sidekiq.rb#10
    def configuration; end

    # source://rspec-sidekiq//lib/rspec/sidekiq/sidekiq.rb#6
    def configure(&block); end
  end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/configuration.rb#8
class RSpec::Sidekiq::Configuration
  # source://rspec-sidekiq//lib/rspec/sidekiq/configuration.rb#13
  def initialize; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/configuration.rb#9
  def clear_all_enqueued_jobs; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/configuration.rb#9
  def clear_all_enqueued_jobs=(_arg0); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/configuration.rb#9
  def enable_terminal_colours; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/configuration.rb#9
  def enable_terminal_colours=(_arg0); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/configuration.rb#23
  def sidekiq_gte_7?; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/configuration.rb#27
  def sidekiq_gte_8?; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/configuration.rb#31
  def silence_warning(symbol); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/configuration.rb#35
  def warn_for?(symbol); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/configuration.rb#9
  def warn_when_jobs_not_processed_by_sidekiq; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/configuration.rb#9
  def warn_when_jobs_not_processed_by_sidekiq=(_arg0); end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#5
module RSpec::Sidekiq::Matchers
  include ::RSpec::Mocks::ArgumentMatchers

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_delayed.rb#8
  def be_delayed(*expected_arguments); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_expired_in.rb#6
  def be_expired_in(expected_argument); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_processed_in.rb#6
  def be_processed_in(expected_queue); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_retryable.rb#6
  def be_retryable(expected_retry); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#6
  def be_unique; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/enqueue_sidekiq_job.rb#82
  def enqueue_sidekiq_job(job_class = T.unsafe(nil)); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/have_enqueued_sidekiq_job.rb#6
  def have_enqueued_sidekiq_job(*expected_arguments); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/save_backtrace.rb#6
  def save_backtrace(expected_backtrace = T.unsafe(nil)); end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#180
class RSpec::Sidekiq::Matchers::Base
  include ::RSpec::Mocks::ArgumentMatchers
  include ::RSpec::Matchers::Composable

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#186
  def initialize; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#184
  def actual_jobs; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#197
  def at(timestamp); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#242
  def at_least(n); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#247
  def at_most(n); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#327
  def common_message; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#335
  def count_message; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#289
  def description; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#237
  def exactly(n); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#184
  def expected_arguments; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#184
  def expected_count; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#184
  def expected_options; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#293
  def failure_message; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#346
  def failure_message_when_negated; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#353
  def formatted(thing); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#207
  def immediately; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#202
  def in(interval); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#184
  def klass; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#217
  def never; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#357
  def normalize_arguments(args); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#212
  def on(queue); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#222
  def once; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#331
  def prefix_message; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#277
  def set_expected_count(relativity, n); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#232
  def thrice; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#255
  def time; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#252
  def times; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#227
  def twice; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#192
  def with(*expected_arguments); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#257
  def with_context(**kwargs); end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_delayed.rb#12
class RSpec::Sidekiq::Matchers::BeDelayed
  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_delayed.rb#13
  def initialize(*expected_arguments); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_delayed.rb#21
  def description; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_delayed.rb#29
  def failure_message; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_delayed.rb#56
  def failure_message_when_negated; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_delayed.rb#33
  def for(interval); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_delayed.rb#38
  def matches?(expected_method); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_delayed.rb#60
  def until(time); end

  private

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_delayed.rb#67
  def find_job(method, arguments, &block); end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_expired_in.rb#10
class RSpec::Sidekiq::Matchers::BeExpiredIn
  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_expired_in.rb#11
  def initialize(expected_argument); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_expired_in.rb#15
  def description; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_expired_in.rb#19
  def failure_message; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_expired_in.rb#23
  def failure_message_when_negated; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_expired_in.rb#27
  def matches?(job); end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_processed_in.rb#10
class RSpec::Sidekiq::Matchers::BeProcessedIn
  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_processed_in.rb#11
  def initialize(expected_queue); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_processed_in.rb#15
  def description; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_processed_in.rb#19
  def failure_message; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_processed_in.rb#33
  def failure_message_when_negated; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_processed_in.rb#23
  def matches?(job); end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_retryable.rb#10
class RSpec::Sidekiq::Matchers::BeRetryable
  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_retryable.rb#11
  def initialize(expected_retry); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_retryable.rb#15
  def description; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_retryable.rb#25
  def failure_message; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_retryable.rb#35
  def failure_message_when_negated; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_retryable.rb#29
  def matches?(job); end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#10
class RSpec::Sidekiq::Matchers::BeUnique
  class << self
    # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#11
    def new; end
  end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#21
class RSpec::Sidekiq::Matchers::BeUnique::Base
  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#22
  def description; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#62
  def expiration_matches?; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#26
  def failure_message; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#66
  def failure_message_when_negated; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#44
  def for(interval); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#58
  def interval_matches?; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#54
  def interval_specified?; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#38
  def matches?(job); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#49
  def until(expiration); end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#89
class RSpec::Sidekiq::Matchers::BeUnique::SidekiqEnterprise < ::RSpec::Sidekiq::Matchers::BeUnique::Base
  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#94
  def actual_expiration; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#90
  def actual_interval; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#106
  def unique_key; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#98
  def value_matches?; end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#71
class RSpec::Sidekiq::Matchers::BeUnique::SidekiqUniqueJobs < ::RSpec::Sidekiq::Matchers::BeUnique::Base
  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#76
  def actual_expiration; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#72
  def actual_interval; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#84
  def unique_key; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#80
  def value_matches?; end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/enqueue_sidekiq_job.rb#7
class RSpec::Sidekiq::Matchers::EnqueueSidekiqJob < ::RSpec::Sidekiq::Matchers::Base
  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/enqueue_sidekiq_job.rb#10
  def initialize(job_class); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/enqueue_sidekiq_job.rb#21
  def matches?(proc); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/enqueue_sidekiq_job.rb#8
  def original_jobs; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/enqueue_sidekiq_job.rb#31
  def prefix_message; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/enqueue_sidekiq_job.rb#35
  def supports_block_expectations?; end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#90
class RSpec::Sidekiq::Matchers::EnqueuedJob
  extend ::Forwardable

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#95
  def initialize(job); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#111
  def ==(other); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#93
  def [](*args, **_arg1, &block); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#103
  def args; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#107
  def context; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#116
  def eql?(other); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#99
  def jid; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#92
  def job; end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#119
class RSpec::Sidekiq::Matchers::EnqueuedJobs
  include ::Enumerable

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#123
  def initialize(klass); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#142
  def each(&block); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#127
  def includes?(arguments, options, count); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#121
  def jobs; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#146
  def minus!(other); end

  private

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#161
  def arguments_matches?(job, arguments); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#156
  def matches?(job, arguments, options); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#167
  def options_matches?(job, options); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#173
  def unwrap_jobs(jobs); end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/have_enqueued_sidekiq_job.rb#11
class RSpec::Sidekiq::Matchers::HaveEnqueuedSidekiqJob < ::RSpec::Sidekiq::Matchers::Base
  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/have_enqueued_sidekiq_job.rb#12
  def initialize(expected_arguments); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/have_enqueued_sidekiq_job.rb#17
  def matches?(job_class); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/have_enqueued_sidekiq_job.rb#29
  def prefix_message; end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#38
class RSpec::Sidekiq::Matchers::JobArguments
  include ::RSpec::Mocks::ArgumentMatchers

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#41
  def initialize(job); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#44
  def job; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#44
  def job=(_arg0); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#46
  def matches?(expected_args); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#52
  def unwrapped_arguments; end

  private

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#62
  def active_job?; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#83
  def active_job_original_args; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#70
  def deserialized_active_job_args; end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#7
class RSpec::Sidekiq::Matchers::JobOptionParser
  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#10
  def initialize(job); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#8
  def job; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#14
  def matches?(options); end

  private

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#20
  def at_evaluator(value); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#25
  def with_context(**expected_context); end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/save_backtrace.rb#10
class RSpec::Sidekiq::Matchers::SaveBacktrace
  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/save_backtrace.rb#11
  def initialize(expected_backtrace = T.unsafe(nil)); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/save_backtrace.rb#15
  def description; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/save_backtrace.rb#25
  def failure_message; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/save_backtrace.rb#35
  def failure_message_when_negated; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/save_backtrace.rb#29
  def matches?(job); end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/helpers/within_sidekiq_retries_exhausted_block.rb#3
module Sidekiq; end

# source://rspec-sidekiq//lib/rspec/sidekiq/helpers/within_sidekiq_retries_exhausted_block.rb#4
module Sidekiq::Job
  include ::Sidekiq::Job::Options

  mixes_in_class_methods ::Sidekiq::Job::Options::ClassMethods
  mixes_in_class_methods ::Sidekiq::Job::ClassMethods
end

# source://rspec-sidekiq//lib/rspec/sidekiq/helpers/within_sidekiq_retries_exhausted_block.rb#5
module Sidekiq::Job::ClassMethods
  # source://rspec-sidekiq//lib/rspec/sidekiq/helpers/within_sidekiq_retries_exhausted_block.rb#20
  def default_retries_exhausted_exception; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/helpers/within_sidekiq_retries_exhausted_block.rb#11
  def default_retries_exhausted_message; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/helpers/within_sidekiq_retries_exhausted_block.rb#6
  def within_sidekiq_retries_exhausted_block(user_msg = T.unsafe(nil), exception = T.unsafe(nil), &block); end
end
