# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rspec-sidekiq` gem.
# Please instead update this file by running `bin/tapioca gem rspec-sidekiq`.


# source://rspec-sidekiq//lib/rspec/sidekiq/configuration.rb#4
module RSpec; end

# source://rspec-sidekiq//lib/rspec/sidekiq/configuration.rb#5
module RSpec::Sidekiq
  class << self
    # source://rspec-sidekiq//lib/rspec/sidekiq/sidekiq.rb#8
    def configuration; end

    # source://rspec-sidekiq//lib/rspec/sidekiq/sidekiq.rb#4
    def configure(&block); end
  end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/configuration.rb#6
class RSpec::Sidekiq::Configuration
  # source://rspec-sidekiq//lib/rspec/sidekiq/configuration.rb#11
  def initialize; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/configuration.rb#7
  def clear_all_enqueued_jobs; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/configuration.rb#7
  def clear_all_enqueued_jobs=(_arg0); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/configuration.rb#7
  def enable_terminal_colours; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/configuration.rb#7
  def enable_terminal_colours=(_arg0); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/configuration.rb#21
  def sidekiq_gte_7?; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/configuration.rb#25
  def silence_warning(symbol); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/configuration.rb#29
  def warn_for?(symbol); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/configuration.rb#7
  def warn_when_jobs_not_processed_by_sidekiq; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/configuration.rb#7
  def warn_when_jobs_not_processed_by_sidekiq=(_arg0); end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#3
module RSpec::Sidekiq::Matchers
  include ::RSpec::Mocks::ArgumentMatchers

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_delayed.rb#6
  def be_delayed(*expected_arguments); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_expired_in.rb#4
  def be_expired_in(expected_argument); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_processed_in.rb#4
  def be_processed_in(expected_queue); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_retryable.rb#4
  def be_retryable(expected_retry); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#4
  def be_unique; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/enqueue_sidekiq_job.rb#81
  def enqueue_sidekiq_job(job_class = T.unsafe(nil)); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/have_enqueued_sidekiq_job.rb#4
  def have_enqueued_sidekiq_job(*expected_arguments); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/save_backtrace.rb#4
  def save_backtrace(expected_backtrace = T.unsafe(nil)); end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#174
class RSpec::Sidekiq::Matchers::Base
  include ::RSpec::Mocks::ArgumentMatchers
  include ::RSpec::Matchers::Composable

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#180
  def initialize; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#178
  def actual_jobs; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#191
  def at(timestamp); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#231
  def at_least(n); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#236
  def at_most(n); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#296
  def common_message; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#304
  def count_message; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#258
  def description; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#226
  def exactly(n); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#178
  def expected_arguments; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#178
  def expected_count; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#178
  def expected_options; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#262
  def failure_message; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#315
  def failure_message_when_negated; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#322
  def formatted(thing); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#201
  def immediately; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#196
  def in(interval); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#178
  def klass; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#326
  def normalize_arguments(args); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#206
  def on(queue); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#211
  def once; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#300
  def prefix_message; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#246
  def set_expected_count(relativity, n); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#221
  def thrice; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#244
  def time; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#241
  def times; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#216
  def twice; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#186
  def with(*expected_arguments); end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_delayed.rb#10
class RSpec::Sidekiq::Matchers::BeDelayed
  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_delayed.rb#11
  def initialize(*expected_arguments); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_delayed.rb#19
  def description; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_delayed.rb#27
  def failure_message; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_delayed.rb#54
  def failure_message_when_negated; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_delayed.rb#31
  def for(interval); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_delayed.rb#36
  def matches?(expected_method); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_delayed.rb#58
  def until(time); end

  private

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_delayed.rb#65
  def find_job(method, arguments, &block); end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_expired_in.rb#8
class RSpec::Sidekiq::Matchers::BeExpiredIn
  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_expired_in.rb#9
  def initialize(expected_argument); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_expired_in.rb#13
  def description; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_expired_in.rb#17
  def failure_message; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_expired_in.rb#21
  def failure_message_when_negated; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_expired_in.rb#25
  def matches?(job); end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_processed_in.rb#8
class RSpec::Sidekiq::Matchers::BeProcessedIn
  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_processed_in.rb#9
  def initialize(expected_queue); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_processed_in.rb#13
  def description; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_processed_in.rb#17
  def failure_message; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_processed_in.rb#31
  def failure_message_when_negated; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_processed_in.rb#21
  def matches?(job); end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_retryable.rb#8
class RSpec::Sidekiq::Matchers::BeRetryable
  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_retryable.rb#9
  def initialize(expected_retry); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_retryable.rb#13
  def description; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_retryable.rb#23
  def failure_message; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_retryable.rb#33
  def failure_message_when_negated; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_retryable.rb#27
  def matches?(job); end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#8
class RSpec::Sidekiq::Matchers::BeUnique
  class << self
    # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#9
    def new; end
  end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#19
class RSpec::Sidekiq::Matchers::BeUnique::Base
  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#20
  def description; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#24
  def failure_message; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#52
  def failure_message_when_negated; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#39
  def for(interval); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#48
  def interval_matches?; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#44
  def interval_specified?; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#33
  def matches?(job); end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#71
class RSpec::Sidekiq::Matchers::BeUnique::SidekiqEnterprise < ::RSpec::Sidekiq::Matchers::BeUnique::Base
  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#72
  def actual_interval; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#80
  def unique_key; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#76
  def value_matches?; end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#57
class RSpec::Sidekiq::Matchers::BeUnique::SidekiqUniqueJobs < ::RSpec::Sidekiq::Matchers::BeUnique::Base
  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#58
  def actual_interval; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#66
  def unique_key; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/be_unique.rb#62
  def value_matches?; end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/enqueue_sidekiq_job.rb#5
class RSpec::Sidekiq::Matchers::EnqueueSidekiqJob < ::RSpec::Sidekiq::Matchers::Base
  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/enqueue_sidekiq_job.rb#8
  def initialize(job_class); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/enqueue_sidekiq_job.rb#19
  def matches?(proc); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/enqueue_sidekiq_job.rb#6
  def original_jobs; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/enqueue_sidekiq_job.rb#33
  def prefix_message; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/enqueue_sidekiq_job.rb#37
  def supports_block_expectations?; end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#84
class RSpec::Sidekiq::Matchers::EnqueuedJob
  extend ::Forwardable

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#89
  def initialize(job); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#105
  def ==(other); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#87
  def [](*args, **_arg1, &block); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#97
  def args; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#101
  def context; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#110
  def eql?(other); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#93
  def jid; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#86
  def job; end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#113
class RSpec::Sidekiq::Matchers::EnqueuedJobs
  include ::Enumerable

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#117
  def initialize(klass); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#136
  def each(&block); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#121
  def includes?(arguments, options, count); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#115
  def jobs; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#140
  def minus!(other); end

  private

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#155
  def arguments_matches?(job, arguments); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#150
  def matches?(job, arguments, options); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#161
  def options_matches?(job, options); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#167
  def unwrap_jobs(jobs); end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/have_enqueued_sidekiq_job.rb#9
class RSpec::Sidekiq::Matchers::HaveEnqueuedSidekiqJob < ::RSpec::Sidekiq::Matchers::Base
  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/have_enqueued_sidekiq_job.rb#10
  def initialize(expected_arguments); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/have_enqueued_sidekiq_job.rb#15
  def matches?(job_class); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/have_enqueued_sidekiq_job.rb#27
  def prefix_message; end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#36
class RSpec::Sidekiq::Matchers::JobArguments
  include ::RSpec::Mocks::ArgumentMatchers

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#39
  def initialize(job); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#42
  def job; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#42
  def job=(_arg0); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#44
  def matches?(expected_args); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#50
  def unwrapped_arguments; end

  private

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#60
  def active_job?; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#77
  def active_job_original_args; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#64
  def deserialized_active_job_args; end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#5
class RSpec::Sidekiq::Matchers::JobOptionParser
  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#8
  def initialize(job); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#6
  def job; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#12
  def matches?(options); end

  private

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#18
  def at_evaluator(value); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/base.rb#23
  def with_context(**expected_context); end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/matchers/save_backtrace.rb#8
class RSpec::Sidekiq::Matchers::SaveBacktrace
  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/save_backtrace.rb#9
  def initialize(expected_backtrace = T.unsafe(nil)); end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/save_backtrace.rb#13
  def description; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/save_backtrace.rb#23
  def failure_message; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/save_backtrace.rb#33
  def failure_message_when_negated; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/matchers/save_backtrace.rb#27
  def matches?(job); end
end

# source://rspec-sidekiq//lib/rspec/sidekiq/helpers/within_sidekiq_retries_exhausted_block.rb#1
module Sidekiq; end

# source://rspec-sidekiq//lib/rspec/sidekiq/helpers/within_sidekiq_retries_exhausted_block.rb#2
module Sidekiq::Job
  include ::Sidekiq::Job::Options

  mixes_in_class_methods ::Sidekiq::Job::Options::ClassMethods
  mixes_in_class_methods ::Sidekiq::Job::ClassMethods
end

# source://rspec-sidekiq//lib/rspec/sidekiq/helpers/within_sidekiq_retries_exhausted_block.rb#3
module Sidekiq::Job::ClassMethods
  # source://rspec-sidekiq//lib/rspec/sidekiq/helpers/within_sidekiq_retries_exhausted_block.rb#18
  def default_retries_exhausted_exception; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/helpers/within_sidekiq_retries_exhausted_block.rb#9
  def default_retries_exhausted_message; end

  # source://rspec-sidekiq//lib/rspec/sidekiq/helpers/within_sidekiq_retries_exhausted_block.rb#4
  def within_sidekiq_retries_exhausted_block(user_msg = T.unsafe(nil), exception = T.unsafe(nil), &block); end
end
