# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `sidekiq` gem.
# Please instead update this file by running `bin/tapioca gem sidekiq`.


# source://sidekiq//lib/active_job/queue_adapters/sidekiq_adapter.rb#36
module ActiveJob; end

class ActiveJob::Base; end

# source://sidekiq//lib/active_job/queue_adapters/sidekiq_adapter.rb#37
module ActiveJob::QueueAdapters; end

# source://sidekiq//lib/active_job/queue_adapters/sidekiq_adapter.rb#47
class ActiveJob::QueueAdapters::SidekiqAdapter < ::ActiveJob::QueueAdapters::AbstractAdapter
  # source://sidekiq//lib/active_job/queue_adapters/sidekiq_adapter.rb#63
  def enqueue(job); end

  # source://sidekiq//lib/active_job/queue_adapters/sidekiq_adapter.rb#58
  def enqueue_after_transaction_commit?; end

  # source://sidekiq//lib/active_job/queue_adapters/sidekiq_adapter.rb#79
  def enqueue_all(jobs); end

  # source://sidekiq//lib/active_job/queue_adapters/sidekiq_adapter.rb#71
  def enqueue_at(job, timestamp); end

  # source://sidekiq//lib/active_job/queue_adapters/sidekiq_adapter.rb#111
  def stopping?; end
end

# source://sidekiq//lib/active_job/queue_adapters/sidekiq_adapter.rb#115
ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper = Sidekiq::ActiveJob::Wrapper

# source://sidekiq//lib/sidekiq/version.rb#3
module Sidekiq
  class << self
    # source://sidekiq//lib/sidekiq.rb#141
    def configure_client; end

    # source://sidekiq//lib/sidekiq.rb#129
    def configure_embed(&block); end

    # source://sidekiq//lib/sidekiq.rb#102
    def configure_server(&block); end

    # source://sidekiq//lib/sidekiq.rb#90
    def default_configuration; end

    # source://sidekiq//lib/sidekiq.rb#86
    def default_job_options; end

    # source://sidekiq//lib/sidekiq.rb#82
    def default_job_options=(hash); end

    # source://sidekiq//lib/sidekiq.rb#58
    def dump_json(object); end

    # source://sidekiq//lib/sidekiq.rb#66
    def ent?; end

    # source://sidekiq//lib/sidekiq.rb#107
    def freeze!; end

    # source://sidekiq//lib/sidekiq/version.rb#7
    def gem_version; end

    # source://sidekiq//lib/sidekiq.rb#54
    def load_json(string); end

    # source://sidekiq//lib/sidekiq.rb#98
    def loader; end

    # source://sidekiq//lib/sidekiq.rb#94
    def logger; end

    # source://sidekiq//lib/sidekiq.rb#62
    def pro?; end

    # source://sidekiq//lib/sidekiq.rb#74
    def redis(&block); end

    # source://sidekiq//lib/sidekiq.rb#70
    def redis_pool; end

    # source://sidekiq//lib/sidekiq.rb#50
    def server?; end

    # source://sidekiq//lib/sidekiq.rb#78
    def strict_args!(mode = T.unsafe(nil)); end

    # source://sidekiq//lib/sidekiq/transaction_aware_client.rb#46
    def transactional_push!; end

    # source://sidekiq//lib/sidekiq.rb#46
    def ❨╯°□°❩╯︵┻━┻; end
  end
end

# source://sidekiq//lib/active_job/queue_adapters/sidekiq_adapter.rb#8
module Sidekiq::ActiveJob; end

# source://sidekiq//lib/active_job/queue_adapters/sidekiq_adapter.rb#10
class Sidekiq::ActiveJob::Wrapper
  include ::Sidekiq::Job
  include ::Sidekiq::Job::Options
  extend ::Sidekiq::Job::Options::ClassMethods
  extend ::Sidekiq::Job::ClassMethods

  # source://sidekiq//lib/active_job/queue_adapters/sidekiq_adapter.rb#13
  def perform(job_data); end

  # source://sidekiq//lib/active_job/queue_adapters/sidekiq_adapter.rb#11
  def sidekiq_options_hash; end

  # source://sidekiq//lib/active_job/queue_adapters/sidekiq_adapter.rb#11
  def sidekiq_options_hash=(_arg0); end

  # source://sidekiq//lib/active_job/queue_adapters/sidekiq_adapter.rb#11
  def sidekiq_retries_exhausted_block; end

  # source://sidekiq//lib/active_job/queue_adapters/sidekiq_adapter.rb#11
  def sidekiq_retries_exhausted_block=(_arg0); end

  # source://sidekiq//lib/active_job/queue_adapters/sidekiq_adapter.rb#11
  def sidekiq_retry_in_block; end

  # source://sidekiq//lib/active_job/queue_adapters/sidekiq_adapter.rb#11
  def sidekiq_retry_in_block=(_arg0); end

  class << self
    # source://sidekiq//lib/active_job/queue_adapters/sidekiq_adapter.rb#11
    def sidekiq_options_hash; end

    # source://sidekiq//lib/active_job/queue_adapters/sidekiq_adapter.rb#11
    def sidekiq_options_hash=(val); end

    # source://sidekiq//lib/active_job/queue_adapters/sidekiq_adapter.rb#11
    def sidekiq_retries_exhausted_block; end

    # source://sidekiq//lib/active_job/queue_adapters/sidekiq_adapter.rb#11
    def sidekiq_retries_exhausted_block=(val); end

    # source://sidekiq//lib/active_job/queue_adapters/sidekiq_adapter.rb#11
    def sidekiq_retry_in_block; end

    # source://sidekiq//lib/active_job/queue_adapters/sidekiq_adapter.rb#11
    def sidekiq_retry_in_block=(val); end

    private

    # source://sidekiq//lib/active_job/queue_adapters/sidekiq_adapter.rb#11
    def __synchronized_sidekiq_options_hash; end

    # source://sidekiq//lib/active_job/queue_adapters/sidekiq_adapter.rb#11
    def __synchronized_sidekiq_retries_exhausted_block; end

    # source://sidekiq//lib/active_job/queue_adapters/sidekiq_adapter.rb#11
    def __synchronized_sidekiq_retry_in_block; end
  end
end

# source://sidekiq//lib/sidekiq/client.rb#8
class Sidekiq::Client
  include ::Sidekiq::TestingClient
  include ::Sidekiq::JobUtil

  # source://sidekiq//lib/sidekiq/client.rb#45
  def initialize(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/client.rb#64
  def cancel!(jid); end

  # source://sidekiq//lib/sidekiq/client.rb#23
  def middleware(&block); end

  # source://sidekiq//lib/sidekiq/client.rb#101
  def push(item); end

  # source://sidekiq//lib/sidekiq/client.rb#134
  def push_bulk(items); end

  # source://sidekiq//lib/sidekiq/client.rb#31
  def redis_pool; end

  # source://sidekiq//lib/sidekiq/client.rb#31
  def redis_pool=(_arg0); end

  private

  # source://sidekiq//lib/sidekiq/client.rb#277
  def atomic_push(conn, payloads); end

  # source://sidekiq//lib/sidekiq/client.rb#253
  def raw_push(payloads); end

  class << self
    # source://sidekiq//lib/sidekiq/client.rb#218
    def enqueue(klass, *args); end

    # source://sidekiq//lib/sidekiq/client.rb#246
    def enqueue_in(interval, klass, *args); end

    # source://sidekiq//lib/sidekiq/client.rb#225
    def enqueue_to(queue, klass, *args); end

    # source://sidekiq//lib/sidekiq/client.rb#232
    def enqueue_to_in(queue, interval, klass, *args); end

    # source://sidekiq//lib/sidekiq/client.rb#202
    def push(item); end

    # source://sidekiq//lib/sidekiq/client.rb#206
    def push_bulk(*_arg0, **_arg1, &_arg2); end

    # source://sidekiq//lib/sidekiq/client.rb#192
    def via(pool); end
  end
end

# source://sidekiq//lib/sidekiq/middleware/modules.rb#22
Sidekiq::ClientMiddleware = Sidekiq::ServerMiddleware

# source://sidekiq//lib/sidekiq/component.rb#24
module Sidekiq::Component
  # source://sidekiq//lib/sidekiq/component.rb#25
  def config; end

  # source://sidekiq//lib/sidekiq/component.rb#118
  def default_tag(dir = T.unsafe(nil)); end

  # source://sidekiq//lib/sidekiq/component.rb#79
  def fire_event(event, options = T.unsafe(nil)); end

  # source://sidekiq//lib/sidekiq/component.rb#75
  def handle_exception(ex, ctx = T.unsafe(nil)); end

  # source://sidekiq//lib/sidekiq/component.rb#63
  def hostname; end

  # source://sidekiq//lib/sidekiq/component.rb#71
  def identity; end

  # source://sidekiq//lib/sidekiq/component.rb#100
  def inspect; end

  # source://sidekiq//lib/sidekiq/component.rb#51
  def logger; end

  # source://sidekiq//lib/sidekiq/component.rb#33
  def mono_ms; end

  # source://sidekiq//lib/sidekiq/component.rb#67
  def process_nonce; end

  # source://sidekiq//lib/sidekiq/component.rb#28
  def real_ms; end

  # source://sidekiq//lib/sidekiq/component.rb#55
  def redis(&block); end

  # source://sidekiq//lib/sidekiq/component.rb#44
  def safe_thread(name, priority: T.unsafe(nil), &block); end

  # source://sidekiq//lib/sidekiq/component.rb#59
  def tid; end

  # source://sidekiq//lib/sidekiq/component.rb#37
  def watchdog(last_words); end
end

# source://sidekiq//lib/sidekiq/config.rb#8
class Sidekiq::Config
  extend ::Forwardable

  # source://sidekiq//lib/sidekiq/config.rb#63
  def initialize(options = T.unsafe(nil)); end

  # source://sidekiq//lib/sidekiq/config.rb#71
  def [](*args, **_arg1, &block); end

  # source://sidekiq//lib/sidekiq/config.rb#71
  def []=(*args, **_arg1, &block); end

  # source://sidekiq//lib/sidekiq/config.rb#252
  def average_scheduled_poll_interval=(interval); end

  # source://sidekiq//lib/sidekiq/config.rb#134
  def capsule(name); end

  # source://sidekiq//lib/sidekiq/config.rb#72
  def capsules; end

  # source://sidekiq//lib/sidekiq/config.rb#117
  def client_middleware; end

  # source://sidekiq//lib/sidekiq/config.rb#91
  def concurrency; end

  # source://sidekiq//lib/sidekiq/config.rb#87
  def concurrency=(val); end

  # source://sidekiq//lib/sidekiq/config.rb#243
  def death_handlers; end

  # source://sidekiq//lib/sidekiq/config.rb#129
  def default_capsule(&block); end

  # source://sidekiq//lib/sidekiq/config.rb#71
  def dig(*args, **_arg1, &block); end

  # source://sidekiq//lib/sidekiq/config.rb#263
  def error_handlers; end

  # source://sidekiq//lib/sidekiq/config.rb#71
  def fetch(*args, **_arg1, &block); end

  # source://sidekiq//lib/sidekiq/config.rb#228
  def freeze!; end

  # source://sidekiq//lib/sidekiq/config.rb#307
  def handle_exception(ex, ctx = T.unsafe(nil)); end

  # source://sidekiq//lib/sidekiq/config.rb#71
  def has_key?(*args, **_arg1, &block); end

  # source://sidekiq//lib/sidekiq/config.rb#75
  def inspect; end

  # source://sidekiq//lib/sidekiq/config.rb#71
  def key?(*args, **_arg1, &block); end

  # source://sidekiq//lib/sidekiq/config.rb#158
  def local_redis_pool; end

  # source://sidekiq//lib/sidekiq/config.rb#281
  def logger; end

  # source://sidekiq//lib/sidekiq/config.rb#292
  def logger=(logger); end

  # source://sidekiq//lib/sidekiq/config.rb#220
  def lookup(name, default_class = T.unsafe(nil)); end

  # source://sidekiq//lib/sidekiq/config.rb#71
  def merge!(*args, **_arg1, &block); end

  # source://sidekiq//lib/sidekiq/config.rb#164
  def new_redis_pool(size, name = T.unsafe(nil)); end

  # source://sidekiq//lib/sidekiq/config.rb#275
  def on(event, &block); end

  # source://sidekiq//lib/sidekiq/config.rb#113
  def queues; end

  # source://sidekiq//lib/sidekiq/config.rb#109
  def queues=(val); end

  # source://sidekiq//lib/sidekiq/config.rb#152
  def reap(timeout = T.unsafe(nil)); end

  # source://sidekiq//lib/sidekiq/config.rb#149
  def reap_idle_redis_connections(timeout = T.unsafe(nil)); end

  # source://sidekiq//lib/sidekiq/config.rb#186
  def redis; end

  # source://sidekiq//lib/sidekiq/config.rb#145
  def redis=(hash); end

  # source://sidekiq//lib/sidekiq/config.rb#170
  def redis_info; end

  # source://sidekiq//lib/sidekiq/config.rb#154
  def redis_pool; end

  # source://sidekiq//lib/sidekiq/config.rb#209
  def register(name, instance); end

  # source://sidekiq//lib/sidekiq/config.rb#123
  def server_middleware; end

  # source://sidekiq//lib/sidekiq/config.rb#73
  def thread_priority; end

  # source://sidekiq//lib/sidekiq/config.rb#73
  def thread_priority=(_arg0); end

  # source://sidekiq//lib/sidekiq/config.rb#81
  def to_json(*_arg0); end

  # source://sidekiq//lib/sidekiq/config.rb#95
  def total_concurrency; end

  private

  # source://sidekiq//lib/sidekiq/config.rb#301
  def parameter_size(handler); end
end

# source://sidekiq//lib/sidekiq/config.rb#11
Sidekiq::Config::DEFAULTS = T.let(T.unsafe(nil), Hash)

# source://sidekiq//lib/sidekiq/config.rb#43
Sidekiq::Config::ERROR_HANDLER = T.let(T.unsafe(nil), Proc)

# source://sidekiq//lib/sidekiq/logger.rb#7
module Sidekiq::Context
  class << self
    # source://sidekiq//lib/sidekiq/logger.rb#20
    def add(k, v); end

    # source://sidekiq//lib/sidekiq/logger.rb#16
    def current; end

    # source://sidekiq//lib/sidekiq/logger.rb#8
    def with(hash); end
  end
end

# source://sidekiq//lib/sidekiq/component.rb#19
Sidekiq::DEFAULT_THREAD_PRIORITY = T.let(T.unsafe(nil), Integer)

# source://sidekiq//lib/sidekiq/testing.rb#83
class Sidekiq::EmptyQueueError < ::RuntimeError; end

# source://sidekiq//lib/sidekiq/iterable_job.rb#34
module Sidekiq::IterableJob
  include ::Sidekiq::Job::Options
  include ::Sidekiq::Job
  include ::Sidekiq::Job::Iterable

  mixes_in_class_methods ::Sidekiq::Job::Options::ClassMethods
  mixes_in_class_methods ::Sidekiq::Job::ClassMethods
  mixes_in_class_methods ::Sidekiq::Job::Iterable::ClassMethods

  class << self
    # source://sidekiq//lib/sidekiq/iterable_job.rb#35
    def included(base); end
  end
end

# source://sidekiq//lib/sidekiq/job.rb#44
module Sidekiq::Job
  include ::Sidekiq::Job::Options

  mixes_in_class_methods ::Sidekiq::Job::Options::ClassMethods
  mixes_in_class_methods ::Sidekiq::Job::ClassMethods

  # source://sidekiq//lib/sidekiq/job.rb#163
  def _context; end

  # source://sidekiq//lib/sidekiq/job.rb#163
  def _context=(_arg0); end

  # source://sidekiq//lib/sidekiq/job.rb#176
  def interrupted?; end

  # source://sidekiq//lib/sidekiq/job.rb#160
  def jid; end

  # source://sidekiq//lib/sidekiq/job.rb#160
  def jid=(_arg0); end

  # source://sidekiq//lib/sidekiq/job.rb#172
  def logger; end

  class << self
    # source://sidekiq//lib/sidekiq/testing.rb#305
    def clear_all; end

    # source://sidekiq//lib/sidekiq/testing.rb#310
    def drain_all; end

    # source://sidekiq//lib/sidekiq/job.rb#165
    def included(base); end

    # source://sidekiq//lib/sidekiq/testing.rb#300
    def jobs; end
  end
end

# source://sidekiq//lib/sidekiq/job.rb#275
module Sidekiq::Job::ClassMethods
  # source://sidekiq//lib/sidekiq/job.rb#378
  def build_client; end

  # source://sidekiq//lib/sidekiq/testing.rb#264
  def clear; end

  # source://sidekiq//lib/sidekiq/job.rb#363
  def client_push(item); end

  # source://sidekiq//lib/sidekiq/job.rb#276
  def delay(*args); end

  # source://sidekiq//lib/sidekiq/job.rb#280
  def delay_for(*args); end

  # source://sidekiq//lib/sidekiq/job.rb#284
  def delay_until(*args); end

  # source://sidekiq//lib/sidekiq/testing.rb#269
  def drain; end

  # source://sidekiq//lib/sidekiq/testing.rb#294
  def execute_job(worker, args); end

  # source://sidekiq//lib/sidekiq/testing.rb#259
  def jobs; end

  # source://sidekiq//lib/sidekiq/job.rb#296
  def perform_async(*args); end

  # source://sidekiq//lib/sidekiq/job.rb#344
  def perform_at(interval, *args); end

  # source://sidekiq//lib/sidekiq/job.rb#326
  def perform_bulk(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/job.rb#332
  def perform_in(interval, *args); end

  # source://sidekiq//lib/sidekiq/job.rb#301
  def perform_inline(*args); end

  # source://sidekiq//lib/sidekiq/testing.rb#278
  def perform_one; end

  # source://sidekiq//lib/sidekiq/job.rb#304
  def perform_sync(*args); end

  # source://sidekiq//lib/sidekiq/testing.rb#285
  def process_job(job); end

  # source://sidekiq//lib/sidekiq/testing.rb#254
  def queue; end

  # source://sidekiq//lib/sidekiq/job.rb#288
  def queue_as(q); end

  # source://sidekiq//lib/sidekiq/job.rb#292
  def set(options); end

  # source://sidekiq//lib/sidekiq/job.rb#359
  def sidekiq_options(opts = T.unsafe(nil)); end
end

# source://sidekiq//lib/sidekiq/job/iterable.rb#7
class Sidekiq::Job::Interrupted < ::RuntimeError; end

# source://sidekiq//lib/sidekiq/job/iterable/active_record_enumerator.rb#5
module Sidekiq::Job::Iterable
  include ::Sidekiq::Job::Iterable::Enumerators

  mixes_in_class_methods ::Sidekiq::Job::Iterable::ClassMethods

  # source://sidekiq//lib/sidekiq/job/iterable.rb#26
  def initialize; end

  # source://sidekiq//lib/sidekiq/job/iterable.rb#43
  def arguments; end

  # source://sidekiq//lib/sidekiq/job/iterable.rb#88
  def around_iteration; end

  # source://sidekiq//lib/sidekiq/job/iterable.rb#121
  def build_enumerator(*_arg0); end

  # source://sidekiq//lib/sidekiq/job/iterable.rb#55
  def cancel!; end

  # source://sidekiq//lib/sidekiq/job/iterable.rb#69
  def cancelled?; end

  # source://sidekiq//lib/sidekiq/job/iterable.rb#41
  def current_object; end

  # source://sidekiq//lib/sidekiq/job/iterable.rb#73
  def cursor; end

  # source://sidekiq//lib/sidekiq/job/iterable.rb#132
  def each_iteration(*_arg0); end

  # source://sidekiq//lib/sidekiq/job/iterable.rb#136
  def iteration_key; end

  # source://sidekiq//lib/sidekiq/job/iterable.rb#106
  def on_cancel; end

  # source://sidekiq//lib/sidekiq/job/iterable.rb#111
  def on_complete; end

  # source://sidekiq//lib/sidekiq/job/iterable.rb#94
  def on_resume; end

  # source://sidekiq//lib/sidekiq/job/iterable.rb#81
  def on_start; end

  # source://sidekiq//lib/sidekiq/job/iterable.rb#101
  def on_stop; end

  # source://sidekiq//lib/sidekiq/job/iterable.rb#141
  def perform(*args); end

  private

  # source://sidekiq//lib/sidekiq/job/iterable.rb#261
  def assert_enumerator!(enum); end

  # source://sidekiq//lib/sidekiq/job/iterable.rb#298
  def cleanup; end

  # source://sidekiq//lib/sidekiq/job/iterable.rb#183
  def fetch_previous_iteration_state; end

  # source://sidekiq//lib/sidekiq/job/iterable.rb#281
  def flush_state; end

  # source://sidekiq//lib/sidekiq/job/iterable.rb#305
  def handle_completed(completed); end

  # source://sidekiq//lib/sidekiq/job/iterable.rb#179
  def is_cancelled?; end

  # source://sidekiq//lib/sidekiq/job/iterable.rb#198
  def iterate_with_enumerator(enumerator, arguments); end

  # source://sidekiq//lib/sidekiq/job/iterable.rb#317
  def mono_now; end

  # source://sidekiq//lib/sidekiq/job/iterable.rb#254
  def reenqueue_iteration_job; end

  # source://sidekiq//lib/sidekiq/job/iterable.rb#276
  def should_interrupt?; end

  # source://sidekiq//lib/sidekiq/job/iterable.rb#244
  def verify_iteration_time(time_limit); end

  class << self
    # source://sidekiq//lib/sidekiq/job/iterable.rb#13
    def included(base); end
  end
end

# source://sidekiq//lib/sidekiq/job/iterable/active_record_enumerator.rb#7
class Sidekiq::Job::Iterable::ActiveRecordEnumerator
  # source://sidekiq//lib/sidekiq/job/iterable/active_record_enumerator.rb#8
  def initialize(relation, cursor: T.unsafe(nil), **options); end

  # source://sidekiq//lib/sidekiq/job/iterable/active_record_enumerator.rb#22
  def batches; end

  # source://sidekiq//lib/sidekiq/job/iterable/active_record_enumerator.rb#14
  def records; end

  # source://sidekiq//lib/sidekiq/job/iterable/active_record_enumerator.rb#30
  def relations; end

  private

  # source://sidekiq//lib/sidekiq/job/iterable/active_record_enumerator.rb#46
  def relations_size; end
end

# source://sidekiq//lib/sidekiq/job/iterable.rb#50
Sidekiq::Job::Iterable::CANCELLATION_PERIOD = T.let(T.unsafe(nil), String)

# source://sidekiq//lib/sidekiq/job/iterable.rb#18
module Sidekiq::Job::Iterable::ClassMethods
  # source://sidekiq//lib/sidekiq/job/iterable.rb#19
  def method_added(method_name); end
end

# source://sidekiq//lib/sidekiq/job/iterable/csv_enumerator.rb#7
class Sidekiq::Job::Iterable::CsvEnumerator
  # source://sidekiq//lib/sidekiq/job/iterable/csv_enumerator.rb#8
  def initialize(csv); end

  # source://sidekiq//lib/sidekiq/job/iterable/csv_enumerator.rb#23
  def batches(cursor:, batch_size: T.unsafe(nil)); end

  # source://sidekiq//lib/sidekiq/job/iterable/csv_enumerator.rb#16
  def rows(cursor:); end

  private

  # source://sidekiq//lib/sidekiq/job/iterable/csv_enumerator.rb#33
  def count_of_rows_in_file; end
end

# source://sidekiq//lib/sidekiq/job/iterable/enumerators.rb#9
module Sidekiq::Job::Iterable::Enumerators
  # source://sidekiq//lib/sidekiq/job/iterable/enumerators.rb#68
  def active_record_batches_enumerator(relation, cursor:, **options); end

  # source://sidekiq//lib/sidekiq/job/iterable/enumerators.rb#46
  def active_record_records_enumerator(relation, cursor:, **options); end

  # source://sidekiq//lib/sidekiq/job/iterable/enumerators.rb#90
  def active_record_relations_enumerator(relation, cursor:, **options); end

  # source://sidekiq//lib/sidekiq/job/iterable/enumerators.rb#20
  def array_enumerator(array, cursor:); end

  # source://sidekiq//lib/sidekiq/job/iterable/enumerators.rb#129
  def csv_batches_enumerator(csv, cursor:, **options); end

  # source://sidekiq//lib/sidekiq/job/iterable/enumerators.rb#109
  def csv_enumerator(csv, cursor:); end
end

# source://sidekiq//lib/sidekiq/job/iterable.rb#193
Sidekiq::Job::Iterable::STATE_FLUSH_INTERVAL = T.let(T.unsafe(nil), Integer)

# source://sidekiq//lib/sidekiq/job/iterable.rb#196
Sidekiq::Job::Iterable::STATE_TTL = T.let(T.unsafe(nil), Integer)

# source://sidekiq//lib/sidekiq/job.rb#48
module Sidekiq::Job::Options
  mixes_in_class_methods ::Sidekiq::Job::Options::ClassMethods

  class << self
    # source://sidekiq//lib/sidekiq/job.rb#49
    def included(base); end
  end
end

# source://sidekiq//lib/sidekiq/job.rb#56
module Sidekiq::Job::Options::ClassMethods
  # source://sidekiq//lib/sidekiq/job.rb#88
  def get_sidekiq_options; end

  # source://sidekiq//lib/sidekiq/job.rb#92
  def sidekiq_class_attribute(*attrs); end

  # source://sidekiq//lib/sidekiq/job.rb#71
  def sidekiq_options(opts = T.unsafe(nil)); end

  # source://sidekiq//lib/sidekiq/job.rb#84
  def sidekiq_retries_exhausted(&block); end

  # source://sidekiq//lib/sidekiq/job.rb#80
  def sidekiq_retry_in(&block); end
end

# source://sidekiq//lib/sidekiq/job.rb#57
Sidekiq::Job::Options::ClassMethods::ACCESSOR_MUTEX = T.let(T.unsafe(nil), Thread::Mutex)

# source://sidekiq//lib/sidekiq/job.rb#184
class Sidekiq::Job::Setter
  include ::Sidekiq::JobUtil

  # source://sidekiq//lib/sidekiq/job.rb#187
  def initialize(klass, opts); end

  # source://sidekiq//lib/sidekiq/job.rb#205
  def perform_async(*args); end

  # source://sidekiq//lib/sidekiq/job.rb#261
  def perform_at(interval, *args); end

  # source://sidekiq//lib/sidekiq/job.rb#251
  def perform_bulk(args, **options); end

  # source://sidekiq//lib/sidekiq/job.rb#258
  def perform_in(interval, *args); end

  # source://sidekiq//lib/sidekiq/job.rb#215
  def perform_inline(*args); end

  # source://sidekiq//lib/sidekiq/job.rb#249
  def perform_sync(*args); end

  # source://sidekiq//lib/sidekiq/job.rb#197
  def set(options); end

  private

  # source://sidekiq//lib/sidekiq/job.rb#265
  def at(interval); end
end

# source://sidekiq//lib/sidekiq/job_util.rb#7
module Sidekiq::JobUtil
  # source://sidekiq//lib/sidekiq/job_util.rb#43
  def normalize_item(item); end

  # source://sidekiq//lib/sidekiq/job_util.rb#69
  def normalized_hash(item_class); end

  # source://sidekiq//lib/sidekiq/job_util.rb#65
  def now_in_millis; end

  # source://sidekiq//lib/sidekiq/job_util.rb#12
  def validate(item); end

  # source://sidekiq//lib/sidekiq/job_util.rb#21
  def verify_json(item); end

  private

  # source://sidekiq//lib/sidekiq/job_util.rb#109
  def json_unsafe?(item); end
end

# source://sidekiq//lib/sidekiq/job_util.rb#80
Sidekiq::JobUtil::RECURSIVE_JSON_UNSAFE = T.let(T.unsafe(nil), Hash)

# source://sidekiq//lib/sidekiq/job_util.rb#10
Sidekiq::JobUtil::TRANSIENT_ATTRIBUTES = T.let(T.unsafe(nil), Array)

# source://sidekiq//lib/sidekiq.rb#44
Sidekiq::LICENSE = T.let(T.unsafe(nil), String)

# source://sidekiq//lib/sidekiq/loader.rb#4
class Sidekiq::Loader
  include ::Sidekiq::Component

  # source://sidekiq//lib/sidekiq/loader.rb#7
  def initialize(cfg = T.unsafe(nil)); end

  # source://sidekiq//lib/sidekiq/loader.rb#22
  def on_load(name, &block); end

  # source://sidekiq//lib/sidekiq/loader.rb#44
  def run_load_hooks(name); end
end

# source://sidekiq//lib/sidekiq/logger.rb#25
class Sidekiq::Logger < ::Logger; end

# source://sidekiq//lib/sidekiq/logger.rb#26
module Sidekiq::Logger::Formatters; end

# source://sidekiq//lib/sidekiq/logger.rb#27
class Sidekiq::Logger::Formatters::Base < ::Logger::Formatter
  # source://sidekiq//lib/sidekiq/logger.rb#40
  def format_context(ctxt = T.unsafe(nil)); end

  # source://sidekiq//lib/sidekiq/logger.rb#36
  def tid; end
end

# source://sidekiq//lib/sidekiq/logger.rb#28
Sidekiq::Logger::Formatters::Base::COLORS = T.let(T.unsafe(nil), Hash)

# source://sidekiq//lib/sidekiq/logger.rb#70
class Sidekiq::Logger::Formatters::JSON < ::Sidekiq::Logger::Formatters::Base
  # source://sidekiq//lib/sidekiq/logger.rb#71
  def call(severity, time, program_name, message); end
end

# source://sidekiq//lib/sidekiq/logger.rb#58
class Sidekiq::Logger::Formatters::Plain < ::Sidekiq::Logger::Formatters::Base
  # source://sidekiq//lib/sidekiq/logger.rb#59
  def call(severity, time, program_name, message); end
end

# source://sidekiq//lib/sidekiq/logger.rb#52
class Sidekiq::Logger::Formatters::Pretty < ::Sidekiq::Logger::Formatters::Base
  # source://sidekiq//lib/sidekiq/logger.rb#53
  def call(severity, time, program_name, message); end
end

# source://sidekiq//lib/sidekiq/logger.rb#64
class Sidekiq::Logger::Formatters::WithoutTimestamp < ::Sidekiq::Logger::Formatters::Pretty
  # source://sidekiq//lib/sidekiq/logger.rb#65
  def call(severity, time, program_name, message); end
end

# source://sidekiq//lib/sidekiq/version.rb#5
Sidekiq::MAJOR = T.let(T.unsafe(nil), Integer)

# source://sidekiq//lib/sidekiq/middleware/chain.rb#79
module Sidekiq::Middleware; end

# source://sidekiq//lib/sidekiq/middleware/chain.rb#80
class Sidekiq::Middleware::Chain
  include ::Enumerable

  # source://sidekiq//lib/sidekiq/middleware/chain.rb#89
  def initialize(config = T.unsafe(nil)); end

  # source://sidekiq//lib/sidekiq/middleware/chain.rb#119
  def add(klass, *args); end

  # source://sidekiq//lib/sidekiq/middleware/chain.rb#163
  def clear; end

  # source://sidekiq//lib/sidekiq/middleware/chain.rb#99
  def copy_for(capsule); end

  # source://sidekiq//lib/sidekiq/middleware/chain.rb#84
  def each(&block); end

  # source://sidekiq//lib/sidekiq/middleware/chain.rb#155
  def empty?; end

  # source://sidekiq//lib/sidekiq/middleware/chain.rb#95
  def entries; end

  # source://sidekiq//lib/sidekiq/middleware/chain.rb#149
  def exists?(klass); end

  # source://sidekiq//lib/sidekiq/middleware/chain.rb#152
  def include?(klass); end

  # source://sidekiq//lib/sidekiq/middleware/chain.rb#141
  def insert_after(oldklass, newklass, *args); end

  # source://sidekiq//lib/sidekiq/middleware/chain.rb#132
  def insert_before(oldklass, newklass, *args); end

  # source://sidekiq//lib/sidekiq/middleware/chain.rb#169
  def invoke(*args, &block); end

  # source://sidekiq//lib/sidekiq/middleware/chain.rb#125
  def prepend(klass, *args); end

  # source://sidekiq//lib/sidekiq/middleware/chain.rb#107
  def remove(klass); end

  # source://sidekiq//lib/sidekiq/middleware/chain.rb#159
  def retrieve; end

  private

  # source://sidekiq//lib/sidekiq/middleware/chain.rb#178
  def traverse(chain, index, args, &block); end
end

# source://sidekiq//lib/sidekiq/middleware/chain.rb#191
class Sidekiq::Middleware::Entry
  # source://sidekiq//lib/sidekiq/middleware/chain.rb#194
  def initialize(config, klass, *args); end

  # source://sidekiq//lib/sidekiq/middleware/chain.rb#192
  def klass; end

  # source://sidekiq//lib/sidekiq/middleware/chain.rb#200
  def make_new; end
end

# source://sidekiq//lib/sidekiq.rb#43
Sidekiq::NAME = T.let(T.unsafe(nil), String)

# source://sidekiq//lib/sidekiq/testing.rb#110
module Sidekiq::Queues
  class << self
    # source://sidekiq//lib/sidekiq/testing.rb#177
    def [](queue); end

    # source://sidekiq//lib/sidekiq/testing.rb#205
    def clear_all; end

    # source://sidekiq//lib/sidekiq/testing.rb#200
    def clear_for(queue, klass); end

    # source://sidekiq//lib/sidekiq/testing.rb#195
    def delete_for(jid, queue, klass); end

    # source://sidekiq//lib/sidekiq/testing.rb#190
    def jobs_by_class; end

    # source://sidekiq//lib/sidekiq/testing.rb#186
    def jobs_by_queue; end

    # source://sidekiq//lib/sidekiq/testing.rb#193
    def jobs_by_worker; end

    # source://sidekiq//lib/sidekiq/testing.rb#181
    def push(queue, klass, job); end
  end
end

# source://sidekiq//lib/sidekiq/rails.rb#10
class Sidekiq::Rails < ::Rails::Engine; end

# source://sidekiq//lib/sidekiq/rails.rb#11
class Sidekiq::Rails::Reloader
  # source://sidekiq//lib/sidekiq/rails.rb#12
  def initialize(app = T.unsafe(nil)); end

  # source://sidekiq//lib/sidekiq/rails.rb#16
  def call; end

  # source://sidekiq//lib/sidekiq/rails.rb#23
  def inspect; end

  # source://sidekiq//lib/sidekiq/rails.rb#27
  def to_hash; end
end

# source://sidekiq//lib/sidekiq/redis_client_adapter.rb#7
class Sidekiq::RedisClientAdapter
  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#62
  def initialize(options); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#78
  def new_client; end

  private

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#84
  def client_opts(options); end
end

# source://sidekiq//lib/sidekiq/redis_client_adapter.rb#8
Sidekiq::RedisClientAdapter::BaseError = RedisClient::Error

# source://sidekiq//lib/sidekiq/redis_client_adapter.rb#9
Sidekiq::RedisClientAdapter::CommandError = RedisClient::CommandError

# source://sidekiq//lib/sidekiq/redis_client_adapter.rb#54
class Sidekiq::RedisClientAdapter::CompatClient < ::RedisClient::Decorator::Client
  include ::Sidekiq::RedisClientAdapter::CompatMethods

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#57
  def config; end
end

# source://sidekiq//lib/sidekiq/redis_client_adapter.rb#54
class Sidekiq::RedisClientAdapter::CompatClient::Pipeline < ::RedisClient::Decorator::Pipeline
  include ::Sidekiq::RedisClientAdapter::CompatMethods
end

# source://sidekiq//lib/sidekiq/redis_client_adapter.rb#14
module Sidekiq::RedisClientAdapter::CompatMethods
  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def bitfield(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def bitfield_ro(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def del(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#19
  def evalsha(sha, keys, argv); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def exists(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def expire(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def flushdb(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def get(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def hdel(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def hget(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def hgetall(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def hincrby(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def hlen(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def hmget(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def hset(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def hsetnx(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def incr(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def incrby(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#15
  def info; end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def lindex(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def llen(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def lmove(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def lpop(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def lpush(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def lrange(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def lrem(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def mget(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def mset(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def ping(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def pttl(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def publish(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def rpop(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def rpush(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def sadd(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def scard(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def script(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def set(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def sismember(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def smembers(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def srem(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def ttl(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def type(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def unlink(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def zadd(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def zcard(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def zincrby(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def zrange(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def zrem(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def zremrangebyrank(*args, **kwargs); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#34
  def zremrangebyscore(*args, **kwargs); end

  private

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#43
  def method_missing(*args, **_arg1, &block); end

  # source://sidekiq//lib/sidekiq/redis_client_adapter.rb#49
  def respond_to_missing?(name, include_private = T.unsafe(nil)); end
end

# source://sidekiq//lib/sidekiq/redis_client_adapter.rb#26
Sidekiq::RedisClientAdapter::CompatMethods::USED_COMMANDS = T.let(T.unsafe(nil), Array)

# source://sidekiq//lib/sidekiq/redis_client_adapter.rb#12
Sidekiq::RedisClientAdapter::DEPRECATED_COMMANDS = T.let(T.unsafe(nil), Set)

# source://sidekiq//lib/sidekiq/redis_connection.rb#8
module Sidekiq::RedisConnection
  class << self
    # source://sidekiq//lib/sidekiq/redis_connection.rb#10
    def create(options = T.unsafe(nil)); end

    private

    # source://sidekiq//lib/sidekiq/redis_connection.rb#52
    def deep_symbolize_keys(object); end

    # source://sidekiq//lib/sidekiq/redis_connection.rb#92
    def determine_redis_provider; end

    # source://sidekiq//lib/sidekiq/redis_connection.rb#65
    def scrub(options); end

    # source://sidekiq//lib/sidekiq/redis_connection.rb#44
    def wrap(pwd); end
  end
end

# source://sidekiq//lib/sidekiq/middleware/modules.rb#6
module Sidekiq::ServerMiddleware
  # source://sidekiq//lib/sidekiq/middleware/modules.rb#7
  def config; end

  # source://sidekiq//lib/sidekiq/middleware/modules.rb#7
  def config=(_arg0); end

  # source://sidekiq//lib/sidekiq/middleware/modules.rb#12
  def logger; end

  # source://sidekiq//lib/sidekiq/middleware/modules.rb#16
  def redis(&block); end

  # source://sidekiq//lib/sidekiq/middleware/modules.rb#8
  def redis_pool; end
end

# source://sidekiq//lib/sidekiq.rb#151
class Sidekiq::Shutdown < ::Interrupt; end

# source://sidekiq//lib/sidekiq/testing.rb#7
class Sidekiq::Testing
  class << self
    # source://sidekiq//lib/sidekiq/testing.rb#10
    def __global_test_mode; end

    # source://sidekiq//lib/sidekiq/testing.rb#10
    def __global_test_mode=(_arg0); end

    # source://sidekiq//lib/sidekiq/testing.rb#36
    def __local_test_mode; end

    # source://sidekiq//lib/sidekiq/testing.rb#40
    def __local_test_mode=(value); end

    # source://sidekiq//lib/sidekiq/testing.rb#14
    def __set_test_mode(mode); end

    # source://sidekiq//lib/sidekiq/testing.rb#32
    def __test_mode; end

    # source://sidekiq//lib/sidekiq/testing.rb#44
    def disable!(&block); end

    # source://sidekiq//lib/sidekiq/testing.rb#60
    def disabled?; end

    # source://sidekiq//lib/sidekiq/testing.rb#56
    def enabled?; end

    # source://sidekiq//lib/sidekiq/testing.rb#48
    def fake!(&block); end

    # source://sidekiq//lib/sidekiq/testing.rb#64
    def fake?; end

    # source://sidekiq//lib/sidekiq/testing.rb#52
    def inline!(&block); end

    # source://sidekiq//lib/sidekiq/testing.rb#68
    def inline?; end

    # source://sidekiq//lib/sidekiq/testing.rb#72
    def server_middleware; end
  end
end

# source://sidekiq//lib/sidekiq/testing.rb#8
class Sidekiq::Testing::TestModeAlreadySetError < ::RuntimeError; end

# source://sidekiq//lib/sidekiq/testing.rb#85
module Sidekiq::TestingClient
  private

  # source://sidekiq//lib/sidekiq/testing.rb#86
  def atomic_push(conn, payloads); end
end

# source://sidekiq//lib/sidekiq/testing.rb#322
module Sidekiq::TestingExtensions
  # source://sidekiq//lib/sidekiq/testing.rb#323
  def jobs_for(klass); end
end

# source://sidekiq//lib/sidekiq/transaction_aware_client.rb#7
class Sidekiq::TransactionAwareClient
  # source://sidekiq//lib/sidekiq/transaction_aware_client.rb#8
  def initialize(pool: T.unsafe(nil), config: T.unsafe(nil)); end

  # source://sidekiq//lib/sidekiq/transaction_aware_client.rb#18
  def batching?; end

  # source://sidekiq//lib/sidekiq/transaction_aware_client.rb#22
  def push(item); end

  # source://sidekiq//lib/sidekiq/transaction_aware_client.rb#37
  def push_bulk(items); end
end

# source://sidekiq//lib/sidekiq/version.rb#4
Sidekiq::VERSION = T.let(T.unsafe(nil), String)

# source://sidekiq//lib/sidekiq/worker_compatibility_alias.rb#12
Sidekiq::Worker = Sidekiq::Job
