# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `timeout` gem.
# Please instead update this file by running `bin/tapioca gem timeout`.


# source://timeout//lib/timeout.rb#21
module Timeout
  private

  # source://timeout//lib/timeout.rb#235
  def timeout(*args, &block); end

  class << self
    # source://timeout//lib/timeout.rb#202
    def timeout(sec, klass = T.unsafe(nil), message = T.unsafe(nil), &block); end
  end
end

# source://timeout//lib/timeout.rb#33
class Timeout::Error < ::RuntimeError
  class << self
    # source://timeout//lib/timeout.rb#34
    def handle_timeout(message); end
  end
end

# source://timeout//lib/timeout.rb#26
class Timeout::ExitException < ::Exception
  # source://timeout//lib/timeout.rb#27
  def exception(*_arg0); end
end

# source://timeout//lib/timeout.rb#49
Timeout::GET_TIME = T.let(T.unsafe(nil), Method)

# source://timeout//lib/timeout.rb#134
class Timeout::Request
  # source://timeout//lib/timeout.rb#137
  def initialize(thread, timeout, exception_class, message); end

  # source://timeout//lib/timeout.rb#135
  def deadline; end

  # source://timeout//lib/timeout.rb#147
  def done?; end

  # source://timeout//lib/timeout.rb#153
  def expired?(now); end

  # source://timeout//lib/timeout.rb#166
  def finished; end

  # source://timeout//lib/timeout.rb#157
  def interrupt; end
end

# source://timeout//lib/timeout.rb#56
class Timeout::State
  # source://timeout//lib/timeout.rb#59
  def initialize; end

  # source://timeout//lib/timeout.rb#57
  def condvar; end

  # source://timeout//lib/timeout.rb#85
  def create_timeout_thread; end

  # source://timeout//lib/timeout.rb#118
  def ensure_timeout_thread_created; end

  # source://timeout//lib/timeout.rb#57
  def queue; end

  # source://timeout//lib/timeout.rb#57
  def queue_mutex; end

  class << self
    # source://timeout//lib/timeout.rb#80
    def instance; end
  end
end

# source://timeout//lib/timeout.rb#78
Timeout::State::GLOBAL_STATE = T.let(T.unsafe(nil), Timeout::State)

# source://timeout//lib/timeout.rb#23
Timeout::VERSION = T.let(T.unsafe(nil), String)
